cat docker-compose.yaml 
version: "3.3"

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nginx:
    image: "nginx"
    container_name: "nginx-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`nginx-adan.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`adan-whoami.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"


###the adan-whoami.com and nginx-adan.com will be auto discovered by traefik
###can view it on dashboard
