{{- if and (not .Values.mysql.existingSecret) (not .Values.mysql.existingPasswordSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-mysql-exporter.fullname" . }}
  labels:
    {{- include "prometheus-mysql-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  password: "{{ .Values.mysql.pass | b64enc }}"
{{- end }}
