suite: test ingress
templates:
  - ingress.yaml
tests:
  - it: should be empty if ingress is not enabled
    asserts:
      - hasDocuments:
          count: 0
  - it: should have apiVersion extensions/v1beta1 for k8s < 1.14
    set:
      ingress.enabled: true
    capabilities:
      majorVersion: 1
      minorVersion: 13
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: Ingress
      - isAPIVersion:
          of: extensions/v1beta1
  - it: should have apiVersion networking.k8s.io/v1beta1 for k8s >= 1.14 < 1.19
    set:
      ingress.enabled: true
    capabilities:
      majorVersion: 1
      minorVersion: 15
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: Ingress
      - isAPIVersion:
          of: networking.k8s.io/v1beta1
  - it: should match snapshot of default values
    set:
      ingress.enabled: true
    chart:
      version: 1.0.0
      appVersion: 1.0.0
    asserts:
      - matchSnapshot: { }
