name: Codespell

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: pull_request

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git,./charts/kube-prometheus-stack/crds/crd-prometheuses.yaml,./charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml,./charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/apiserver.yaml
          ignore_words_list: iam,aks
          check_filenames: true
          check_hidden: true
