apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-server.fullname" . }}
  labels:
    {{- include "my-server.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "my-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "my-server.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-imagepullsecrets
#      {{- with .Values.imagePullSecrets }}
#      imagePullSecrets:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
      serviceAccountName: {{ include "my-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-my-server
          image: myhub.com/busybox:1.33
          command: ['sh', '-c', 'until nc -vz {{ .Release.Name }}-my-db 3306; do echo waiting for {{ .Release.Name }}-my-db 3306 port; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: zabbix
              containerPort: 10051 
              protocol: TCP
          env:
            - name: DB_SERVER_HOST
              value: {{ .Release.Name }}-my-db
            - name: MYSQL_USER
              value: zabbix
            - name: MYSQL_DATABAS
              value: zabbix 
            - name: MYSQL_PASSWORD
              value: zabbix
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-my-db 
                  key: ROOT_PASSWORD
          readinessProbe:
            tcpSocket:
              port: 10051
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 10051
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
