apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-server.fullname" . }}
  labels:
    {{- include "my-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 10051
      protocol: TCP
      name: zabbix
  selector:
    {{- include "my-server.selectorLabels" . | nindent 4 }}
