apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
    app.kubernetes.io/role:  {{ .Values.custom_label.roleGroup }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "web.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/role:  {{ .Values.custom_label.roleGroup }}
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-imagepullsecrets
#      {{- with .Values.imagePullSecrets }}
#      imagePullSecrets:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
      serviceAccountName: {{ include "web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-server-web
          image: myhub.com/busybox:1.33
          command: ['sh', '-c', 'until nc -vz {{ .Release.Name }}-server 10051; do echo waiting for {{ .Release.Name }}-server 10051 port; sleep 2; done;']
        - name: init-server-db
          image: myhub.com/busybox:1.33
          command: ['sh', '-c', 'until nc -vz {{ .Release.Name }}-db 3306; do echo waiting for {{ .Release.Name }}-server 3306 port; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
              - name: DB_SERVER_HOST
                value: {{ .Release.Name }}-db
              - name: MYSQL_USER
                value: zabbix
              - name: MYSQL_DATABAS
                value: zabbix 
              - name: MYSQL_PASSWORD
                value: zabbix
              - name: ZBX_SERVER_HOST
                value: {{ .Release.Name }}-server 
              - name: PHP_TZ
                value: Asia/Shanghai
              - name: MYSQL_ROOT_PASSWORD 
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-db 
                    key: ROOT_PASSWORD 
 
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
