apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-my-db 
  labels:
    {{- include "my-db.labels" . | nindent 4 }}
type: Opaque
data:
  ROOT_PASSWORD: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk 
